<script lang="ts">
  // /about (PLAN §7): how similarity works, the evaluation record, data notes, hosting, attribution, how to read a
  // pyramid. Every number on this page is read from web/src/data/evals.json (scripts/export_evals.py, regenerated by
  // `make build`) or meta.json — nothing is typed in by hand, so a re-run of the evaluation re-writes the page.
  import { countries, meta } from '../lib/entities.ts';
  import { dataUrl } from '../lib/data.ts';
  import { evals, fmt, fmtPctOf, g1Of, g2Of, imageSpace, orderedMetrics } from '../lib/evals.ts';
  import { METRIC_LABEL } from '../lib/restate.ts';
  import { href } from '../lib/url.ts';
  import { app } from '../lib/state.svelte.ts';
  import { countryQuery, type Metric } from '../lib/router.ts';

  const sigma = meta.sigma;
  const sL2 = sigma.l2['2'];
  const sW1 = sigma.w1sex['2'];
  const sL2t = sigma.l2['1'];
  const sW1t = sigma.w1['1'];
  const nAgg = meta.n_entities - meta.n_countries;
  const nMicro = countries.filter((e) => e.is_micro).length;
  const patch = meta.patches[0] ?? null;
  const exposed = evals.exposed_visual;
  const exposedSpace = exposed ? imageSpace(exposed.model) : undefined;
  const gate = evals.prereg.continuity_gate;
  const visualRows = evals.g1.filter((r) => r.metric.startsWith('visual:'));
  const w1 = g1Of('w1');
  const blend = g1Of('blend');
  const share = evals.blend_w1_share;
  const presets = evals.div_presets ?? { strict: 0, balanced: 0.5, spread: 2 };
  const sweep = evals.beta_sweep ?? [];
  const eraChip = (y: number) => `${y} ${y > app.currentYear ? '(projected)' : y > meta.last_observed_year ? '(nowcast)' : ''}`.trim();
  const menuLabel = (m: string): string => (m.startsWith('visual:') ? `Visual · ${m.slice(7)}` : (METRIC_LABEL[m as Metric] ?? m));
  const example = (id: string, year: number) => href(countryQuery(id, year));
  const noticeUrl = dataUrl(meta.files.notice);
  const built = meta.built.slice(0, 10);
  const evalBuilt = evals.built.slice(0, 10);

  const SECTIONS = [
    ['similarity', 'How similarity works'],
    ['visual', 'The Visual metric'],
    ['record', 'Evaluation record'],
    ['data', 'Data notes'],
    ['projections', 'Why projections converge'],
    ['development', 'Shape is not development'],
    ['reading', 'How to read a pyramid'],
    ['hosting', 'Hosting & privacy'],
    ['attribution', 'Attribution & licences'],
  ] as const;
</script>

<article class="mx-auto max-w-3xl py-6 leading-relaxed">
  <h1 class="text-3xl font-semibold tracking-tight">About</h1>
  <p class="mt-2 text-fg-2">
    Population Pyramid Explorer shows the age structure of {meta.n_countries} countries and {nAgg} regions for every year
    1950–2100, and finds the pyramids most and least like any of them <em>by shape</em>. This page says exactly how,
    with the measured numbers the site itself was built from (data built {built}; evaluation run {evalBuilt}, stage
    “{evals.stage}”).
  </p>
  <nav aria-label="On this page" class="mt-4 flex flex-wrap gap-x-3 gap-y-1 text-sm">
    {#each SECTIONS as [id, label] (id)}
      <a class="underline decoration-border underline-offset-2 hover:decoration-fg" href="#{id}">{label}</a>
    {/each}
  </nav>

  <!-- ============================================================ similarity -->
  <section id="similarity" class="mt-10 space-y-4">
    <h2 class="text-xl font-semibold tracking-tight">How similarity works</h2>
    <p>
      <strong>Shape</strong> is a vector of 42 numbers: the share of the total population in each of 21 five-year age
      bands (0–4 … 95–99, 100+), separately for males and females. Dividing by the total makes the comparison
      size-invariant — Niger and India can be neighbours — but not age-shift-invariant (an older population is a
      different shape) and not sex-swap-invariant (Qatar's male working-age bulge is shape). Shares are never
      re-scaled per bin and never smoothed in storage.
    </p>
    <h3 class="font-semibold">The default metric, “Shape” (<code>blend</code>)</h3>
    <p>Two halves, each divided by its typical value so neither dominates:</p>
    <pre class="overflow-x-auto rounded-md border border-border bg-surface p-3 text-sm"><code>l2   = ‖s42_a − s42_b‖₂                          (bin-by-bin difference)
w1s  = 5 · Σ_k |CM_a,k − CM_b,k| + |CF_a,k − CF_b,k|   (per-sex age movement, in years)
d    = ½ · l2 / σ_L2  +  ½ · w1s / σ_W1
σ_L2 = {fmt(sL2, 4)}   σ_W1 = {fmt(sW1, 3)} y         (two-sex; total-only: {fmt(sL2t, 4)} / {fmt(sW1t, 3)} y)</code></pre>
    <p>
      <code>CM</code>/<code>CF</code> are the cumulative male and female shares up the age ladder, so the second term
      is a Wasserstein-1 (“earth-mover”) distance: how many years of age, on average, the mass of one pyramid has to
      travel to become the other. The σ values are the <em>median distance between random pairs of countries in the same
      year</em>, measured on this corpus at build time, so <code>d = 1</code> means “as far apart as a typical pair”.
      The L2 half is blind to <em>where</em> a difference sits; the W1 half charges a shifted bulge in proportion to how
      far it moved. Every result card decomposes its <code>d</code> into the two halves and the three bins that
      contribute most to each, and the “similar because / differs in” sentences compare summary features (median age,
      65+, under-15, base slope, working-age sex ratio, modal band) z-scored against <em>the query year's</em> country
      set — for both members of a pair, whatever the candidate's year, so a sentence about South Korea 2026 and Japan
      2008 reads the same from a country page and from the compare page.
    </p>

    <h3 class="font-semibold">Why plain age-shift (<code>w1</code>) is not the default</h3>
    <p>
      The one-number Wasserstein distance on the total age distribution is the most interpretable option (“1.97 years
      of average age movement separates them”), and it stays in the menu as <em>{METRIC_LABEL.w1}</em>. It is not the
      default because it collapses to roughly |Δ mean age| and is sex-blind: two pyramids with the same mean age but
      opposite base slopes read as identical. It also failed the continuity gate — the year-to-year nearest neighbour
      of a country is that same country only C1 = {fmt(w1?.c1_obs)} of the time (gate ≥ {gate.c1}; Shape: {fmt(blend?.c1_obs)}),
      so its verdict is “{evals.verdicts.w1?.verdict}” in the record below.
    </p>

    <h3 class="font-semibold">A documented asymmetry in the per-sex term</h3>
    <p>
      The per-sex W1 is unbalanced: male and female shares of the <em>total</em> do not sum to the same mass, and the
      surplus is parked at the 100+ end. A young male surplus (Gulf states) therefore pays roughly 13 bands × 5 years of
      transport, while an elderly female surplus (Japan 80+) pays almost nothing, and both <code>CM</code> and
      <code>CF</code> carry the imbalance. A balanced alternative (<em>{METRIC_LABEL.w1bal}</em>, total-distribution W1 plus a
      sex-ratio term) is under “advanced”. Because σ is fitted over all years pooled, the two halves of Shape are equal
      only on the pooled sample:
    </p>
    {#if share}
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <caption class="sr-only">Median W1 share of the Shape distance by era</caption>
          <thead class="text-left text-xs text-muted"><tr><th class="py-1 pr-3 font-medium">sex</th><th class="py-1 pr-3 font-medium">observed ≤ {meta.last_observed_year}</th><th class="py-1 pr-3 font-medium">nowcast</th><th class="py-1 pr-3 font-medium">projected</th><th class="py-1 font-medium">pooled (σ fit)</th></tr></thead>
          <tbody>
            {#each Object.entries(share) as [sex, row] (sex)}
              <tr class="border-t border-border tabular-nums"><td class="py-1 pr-3">{sex === '2' ? 'two-sex' : 'total only'}</td><td class="py-1 pr-3">{fmt(row.obs, 3)}</td><td class="py-1 pr-3">{fmt(row.nowcast, 3)}</td><td class="py-1 pr-3">{fmt(row.proj, 3)}</td><td class="py-1">{fmt(row.all, 3)}</td></tr>
            {/each}
          </tbody>
        </table>
      </div>
      <p class="text-sm text-fg-2">
        σ_W1 rises into the projections, which tilts observed-year pairs slightly towards the L2 half. The definition
        stands (it is balanced at the 2024–2026 default years); the tilt is recorded rather than hidden.
      </p>
    {/if}

    <h3 class="font-semibold">Trend: motion and path</h3>
    <p>
      The <em>Trend</em> mode compares change instead of a snapshot, over a window L of 5, 10 or 20 years.
      <strong>Motion</strong> is the distance between the two L-year changes in the 42 shares (who is moving the same
      way, regardless of where they are; σ<sub>trend@10</sub> = {fmt(sigma['trend@10']?.['2'], 4)}). <strong>Path</strong> is the
      mean Shape distance over the aligned L-year path (who is at the same place <em>and</em> moving the same way). Both
      passed continuity (motion C1 {fmt(g1Of('trend')?.c1_obs)}, path {fmt(g1Of('path')?.c1_obs)}); motion is a
      level-free signal, so it disagrees with every snapshot label set by construction and is offered for what it is.
    </p>

    <h3 class="font-semibold">“Most different” and diversity</h3>
    <p>
      Opposites are the farthest pyramids under the active metric over the same candidate set as the twins,
      <em>diversified</em> with a maximal-marginal-relevance step: the pool is the farthest quartile; the first choice is
      the farthest; each next choice maximises <code>d(q, x) + β · min_s d(x, s)</code> against the choices so far. Three
      presets: strict (β = {presets.strict}) is plain farthest-k, balanced (β = {presets.balanced}, default) keeps about
      two thirds of the strict list, spread (β = {presets.spread}) about a third. <strong>The raw rank is never
      hidden</strong>: every opposite card says “#7 farthest”, and a strip under the cards lists the strictly farthest
      set whenever diversity changed it.
    </p>
    {#if sweep.length}
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <caption class="sr-only">β sweep on the 2024 country anchors</caption>
          <thead class="text-left text-xs text-muted"><tr><th class="py-1 pr-3 font-medium">β</th><th class="py-1 pr-3 font-medium">top-5 Jaccard vs strict</th><th class="py-1 pr-3 font-medium">mean raw rank</th><th class="py-1 font-medium">mean UN regions among 5</th></tr></thead>
          <tbody>
            {#each sweep as r (r.beta)}
              <tr class="border-t border-border tabular-nums"><td class="py-1 pr-3">{r.beta}</td><td class="py-1 pr-3">{fmt(r.jaccard_vs_strict, 2)}</td><td class="py-1 pr-3">{fmt(r.mean_raw_rank, 1)}</td><td class="py-1">{fmt(r.mean_regions, 2)}</td></tr>
            {/each}
          </tbody>
        </table>
      </div>
      <p class="text-sm text-fg-2">
        Diversity works over <em>shape</em> distance, not region or class: for an old anchor the farthest quartile is
        entirely young Sahel and Gulf pyramids, so no β yields regional variety (mean regions stays near 2 at every β).
        The site therefore never promises it.
      </p>
    {/if}

    <h3 class="font-semibold">Percentile bands</h3>
    <p>
      “very close / close / typical / far / extreme” place a distance against the right null: for a same-year pair, the
      distribution of random country pairs <em>in that year</em> (the scale drifts — random pairs were closer in 1950
      and will be closer again by 2100 as projections converge, so pooled tables would mislabel both ends); for a
      cross-year pair, random pairs with the query's decade and era; for a time-shift row, the distribution of
      <em>best-year</em> matches, which is what “closer than 93 % of best-year matches” means. Cut-points are p5 / p25 /
      p75 / p95 on a {meta.bands_grid.length}-point quantile grid; percentiles are interpolated and shown as “≈”.
    </p>
  </section>

  <!-- ============================================================ visual -->
  <section id="visual" class="mt-10 space-y-4">
    <h2 class="text-xl font-semibold tracking-tight">The Visual metric — a pre-registered experiment</h2>
    <p>
      The tempting shortcut is to render every pyramid, embed the picture with a vision model and retrieve nearest
      pictures. It was tested as an experiment with the gates written down first (<code>evals/image_embeddings.md</code>),
      not adopted as the architecture. Two encoders were run on text-free canonical renders of all {evals.n_rows.toLocaleString('en-US')}
      pyramids — SigLIP 2 (base, naflex, one 16-px patch row per age band) and DINOv2 (base) — pooled, L2-normalised and
      reduced to 64 dimensions without whitening. Continuity gate: {gate.definition}; gate C1 ≥ {gate.c1}, C5 ≥ {gate.c5} on {gate.span}.
    </p>
    <h3 class="font-semibold">Pre-registered predictions</h3>
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <caption class="sr-only">Pre-registered predictions for the image-embedding experiment</caption>
        <thead class="text-left text-xs text-muted"><tr><th class="py-1 pr-3 font-medium">id</th><th class="py-1 pr-3 font-medium">prediction</th><th class="py-1 pr-3 font-medium">gate</th><th class="py-1 font-medium">measured</th></tr></thead>
        <tbody>
          {#each evals.prereg.image_predictions as p (p.id)}
            {@const scored = evals.image_spaces.map((s) => ({ model: s.model, hit: s.predictions_scored.find((q) => q.id === p.id || q.id.split('/').includes(p.id)) }))}
            <tr class="border-t border-border align-top">
              <td class="py-1 pr-3 font-mono text-xs">{p.id}</td>
              <td class="py-1 pr-3">{p.prediction}</td>
              <td class="py-1 pr-3 text-fg-2">{p.gate}</td>
              <td class="py-1 tabular-nums text-fg-2">
                {#if p.id === 'P3'}
                  {#each evals.image_spaces as s (s.model)}<div>{s.model}: HK agreement {fmt(s.hk_family)} → {s.hk_family !== null && s.hk_family >= evals.gates.reject_hk ? 'met' : 'not met'}</div>{/each}
                {:else if p.id === 'P4'}
                  <span class="text-muted">awaits the M4 triplets</span>
                {:else if scored.some((s) => s.hit)}
                  {#each scored as s (s.model)}{#if s.hit}<div>{s.model}: {fmt(s.hit.observed)} → {s.hit.met ? 'met' : 'NOT met'}</div>{/if}{/each}
                {:else}
                  <span class="text-muted">—</span>
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
    <h3 class="font-semibold">What was measured</h3>
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <caption class="sr-only">Image spaces against the numeric default</caption>
        <thead class="text-left text-xs text-muted"><tr><th class="py-1 pr-3 font-medium">space</th><th class="py-1 pr-3 font-medium">C1 obs (gate ≥ {gate.c1})</th><th class="py-1 pr-3 font-medium">C5 obs (≥ {gate.c5})</th><th class="py-1 pr-3 font-medium">ρ vs Shape</th><th class="py-1 pr-3 font-medium">top-10 overlap with Shape</th><th class="py-1 pr-3 font-medium">HK class agreement</th><th class="py-1 font-medium">verdict</th></tr></thead>
        <tbody>
          {#each evals.image_spaces as s (s.model)}
            <tr class="border-t border-border tabular-nums">
              <td class="py-1 pr-3 font-mono text-xs">{s.model}{exposed?.model === s.model ? ' · exposed as “Visual”' : ''}</td>
              <td class="py-1 pr-3">{fmt(s.c1)} ✗</td>
              <td class="py-1 pr-3">{fmt(s.c5)} ✗</td>
              <td class="py-1 pr-3">{fmt(s.spearman_vs_blend, 2)}</td>
              <td class="py-1 pr-3">{fmtPctOf(s.top10_overlap)} same-year · {fmtPctOf(s.top10_overlap_anyyear)} any-year</td>
              <td class="py-1 pr-3">{fmt(s.hk_family)}</td>
              <td class="py-1">{s.verdict}{s.verdict !== s.expected_verdict ? ` (predicted ${s.expected_verdict})` : ''}</td>
            </tr>
          {/each}
          {#if blend}
            <tr class="border-t border-border tabular-nums text-fg-2"><td class="py-1 pr-3">Shape (for scale)</td><td class="py-1 pr-3">{fmt(blend.c1_obs)} ✓</td><td class="py-1 pr-3">{fmt(blend.c5_obs)} ✓</td><td class="py-1 pr-3">1</td><td class="py-1 pr-3">—</td><td class="py-1 pr-3">{fmt(g2Of('blend')?.hk_family)}</td><td class="py-1">{evals.verdicts.blend?.verdict}</td></tr>
          {/if}
        </tbody>
      </table>
    </div>
    <p>
      Read: the embeddings are <em>related</em> to shape (rank correlation {fmt(exposedSpace?.spearman_vs_blend, 2)} with
      Shape distance; class agreement above the {evals.gates.reject_hk} floor, so P3 held) but they are not continuous
      in time — a country's nearest picture is its own adjacent year only {fmt(visualRows[0]?.c1_obs, 2)}–{fmt(visualRows[visualRows.length - 1]?.c1_obs, 2)} of the
      time against a gate of {gate.c1}, and their top-10 lists share under a third of their members with Shape's. The
      invariance diagnostic explains why: recolouring the bars or adding a 2-px gap moves a render's embedding farther
      from itself than the nearest <em>different</em> pyramid sits, so these encoders separate rendering styles more
      than they separate populations. Both spaces were predicted to land at “{evals.prereg.expected_visual_verdict}” and
      landed one rung lower, at “{visualRows[0] ? evals.verdicts[visualRows[0].metric]?.verdict : '—'}”.
    </p>
    <p>
      <strong>Why it ships anyway.</strong> By the owner's decision both methods are available: Shape is the default,
      and the image space with the better observed-span continuity ({exposed?.model}, rule: {exposed?.rule ?? 'better observed-span G1 C1'})
      is in the metric menu as “Visual”, labelled experimental, so anyone can see for themselves what a vision model
      thinks looks alike — and compare it with the numbers above. {#if exposed?.alternates?.length}The other space
      ({exposed.alternates.join(', ')}) is reachable by URL only.{/if} The human-triplet test (P4) has not run yet;
      if it ever favours Visual on notch-and-bulge anchors — the only claim the pre-registration permits — the record
      will say so here.
    </p>
  </section>

  <!-- ============================================================ record -->
  <section id="record" class="mt-10 space-y-4">
    <h2 class="text-xl font-semibold tracking-tight">Evaluation record</h2>
    <p>
      Every metric was scored against label sets frozen from outside this codebase before any metric ran (Korenjak-Černe
      clusters, Hahn-Klimroth rule classes, stage thresholds, RIETI's China-2020 ≈ Japan-1990 window; the Yoshida
      epitome sequence is reported, not gated) plus continuity and an outlier check (the Gulf states must be the most
      isolated pyramids of 2024). The menu is a mechanical consequence of these verdicts; “menu” verdicts marked
      provisional await the human-triplet test.
    </p>
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <caption class="sr-only">Verdict per metric with the gated numbers</caption>
        <thead class="text-left text-xs text-muted"><tr><th class="py-1 pr-3 font-medium">metric</th><th class="py-1 pr-3 font-medium">in the app</th><th class="py-1 pr-3 font-medium">C1 obs</th><th class="py-1 pr-3 font-medium">C5 obs</th><th class="py-1 pr-3 font-medium">KC 2006</th><th class="py-1 pr-3 font-medium">HK family</th><th class="py-1 pr-3 font-medium">stage</th><th class="py-1 pr-3 font-medium">CHN 2020 → JPN</th><th class="py-1 font-medium">verdict</th></tr></thead>
        <tbody>
          {#each orderedMetrics() as m (m)}
            {@const r1 = g1Of(m)}
            {@const r2 = g2Of(m)}
            {@const v = evals.verdicts[m]}
            <tr class="border-t border-border tabular-nums">
              <td class="py-1 pr-3 font-mono text-xs">{m}</td>
              <td class="py-1 pr-3 text-fg-2">{menuLabel(m)}</td>
              <td class="py-1 pr-3">{fmt(r1?.c1_obs)} {r1?.c1_obs !== null && r1?.c1_obs !== undefined ? (r1.c1_obs >= gate.c1 ? '✓' : '✗') : ''}</td>
              <td class="py-1 pr-3">{fmt(r1?.c5_obs)} {r1?.c5_obs !== null && r1?.c5_obs !== undefined ? (r1.c5_obs >= gate.c5 ? '✓' : '✗') : ''}</td>
              <td class="py-1 pr-3">{fmt(r2?.kc2006)}</td>
              <td class="py-1 pr-3">{fmt(r2?.hk_family)}</td>
              <td class="py-1 pr-3">{fmt(r2?.stage)}</td>
              <td class="py-1 pr-3">{r2?.rieti_best_year ?? '—'}</td>
              <td class="py-1">{v?.verdict}{v?.provisional ? '*' : ''}{v?.scope ? ` (${v.scope})` : ''}{#if v?.shipped && v.shipped !== v.verdict}<span class="block text-xs text-muted" title={v.shipped_note}>ships as “{v.shipped}”†</span>{/if}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
    <p class="text-xs text-muted">
      Gates: C1 ≥ {evals.gates.c1}, C5 ≥ {evals.gates.c5}, Korenjak-Černe 2006 agreement ≥ {evals.gates.kc_agree}, Hahn-Klimroth family
      agreement ≥ {evals.gates.hk_agree}, stage agreement ≥ {evals.gates.stage_agree}, CHN 2020 best Japan year ∈ [1985, 1995]; “rejected”
      = C1 &lt; {evals.gates.lab_c1} or class agreement &lt; {evals.gates.reject_hk}. * provisional until the M4 triplets.
      † an evaluation-only metric with no percentile tables in the build is capped at “lab” (URL-only) in the app.
      Full tables, the β sweep and the findings: <code>evals/RESULTS.md</code> in the repository (data hash
      <code>{evals.data_hash.slice(0, 16)}…</code>).
    </p>
    <ul class="list-disc space-y-1 pl-5 text-sm text-fg-2">
      {#each evals.notes as n, i (i)}<li>{n}</li>{/each}
    </ul>
    <p class="text-sm">
      <a class="underline" href={href({ kind: 'static', page: 'evidence' })}>Evidence page — what the literature found, what happened after China 1990, and this site's own pre-registered backtest</a>
    </p>
  </section>

  <!-- ============================================================ data -->
  <section id="data" class="mt-10 space-y-4">
    <h2 class="text-xl font-semibold tracking-tight">Data notes</h2>
    <ul class="list-disc space-y-2 pl-5">
      <li>
        <strong>Source.</strong> United Nations <em>World Population Prospects 2024</em>, medium variant, population on
        1 July by five-year age group and sex, 1950–2100. Years up to {meta.last_observed_year} are the UN's estimates;
        later years are projections. {meta.n_countries} countries and areas (every WPP “Country/Area” row) plus {nAgg}
        aggregates — the world, geographic regions and subregions, SDG regions, income and development groups.
      </li>
      <li>
        <strong>Present borders.</strong> The UN back-casts every series within today's borders, so “Germany 1960”
        is the population of the territory of present-day Germany in 1960, not of either German state; the same holds
        for the successor states of the USSR, Yugoslavia, Sudan/South Sudan and others.
      </li>
      <li>
        <strong>Names.</strong> Brief display names are used in the interface (Taiwan, Kosovo, South Korea, Türkiye…),
        with the UN name as the subtitle on each page (for example “China, Taiwan Province of China” and “Kosovo (under
        UNSC res. 1244)”). Any ISO code, UN name or common alias works in a URL.
      </li>
      {#if patch}
        <li>
          <strong>Togo interim update.</strong> On 19 January 2026 the UN issued an interim update for Togo after its
          2022 census; this site applies it (patch <code>{patch.id}</code>{patch.applied ? '' : ' — NOT applied in this build'}).
          Because the UN did not revise aggregates, the {patch.recomputed_aggregates.length} aggregates containing Togo
          are recomputed from their members here, so World, Africa, Western Africa and the income/development groups
          differ slightly from the UN's published totals. {patch.note}
        </li>
      {/if}
      <li>
        <strong>Microstates.</strong> {nMicro} of the {meta.n_countries} countries have fewer than 100,000 people in 2026.
        Their pyramids are noisy (a few hundred people move a band by a percent), so the default candidate floor is a
        population of 100k in the candidate's own year; set it to 10k or none to include them.
      </li>
      <li>
        <strong>Nowcast years.</strong> Years after {meta.last_observed_year} up to the current year
        ({meta.last_observed_year + 1}–{app.currentYear}) are projections too, but near enough to count as “now”; they
        are included in the observed-era default and tagged “nowcast”. The current year is your device's clock.
      </li>
      <li>
        <strong>Five-year bands, 16-bit shares.</strong> Ages are stored in 21 five-year bands with 100+ open-ended.
        Each pyramid's 42 shares are quantised to 16 bits with largest-remainder rounding so every row sums to exactly
        65,535 (a resolution of ≈ 0.0015 percentage points, far below the UN's own revision noise); totals are kept as
        floats so absolute numbers reproduce the UN's within a person or two. Files under <code>/data</code> are these
        derivatives, not the UN's files.
      </li>
    </ul>
  </section>

  <section id="projections" class="mt-10 space-y-4">
    <h2 class="text-xl font-semibold tracking-tight">Why projections converge — and the era rule</h2>
    <p>
      The medium variant assumes fertility drifting towards replacement and mortality improving everywhere, so the
      pyramids of 2080 look far more alike than the pyramids of 1980 do. In a literal “any year 1950–2100” search the
      converged future crowds out history: Japan 2024's nearest any-year pyramid would be Latvia 2064. The default for
      cross-year searches is therefore <em>observed + nowcast</em> (≤ the current year) with projections opt-in; a chip
      beside the results counts the hidden projected years and one click includes them.
    </p>
    <p>
      <strong>Querying from a projected year</strong> flips the default: for <a class="underline" href={example('JPN', 2050)}>Japan 2050</a>
      the observed-only rule would exclude the query's own era and let the time-shift panel look only backwards, so
      the era defaults to “all” and the chip inverts to “projections included (query is a projection) · observed only”.
      The <code>era</code> URL parameter is written only when it differs from that default, so a shared link means the
      same thing on any device.
    </p>
  </section>

  <section id="development" class="mt-10 space-y-3">
    <h2 class="text-xl font-semibold tracking-tight">Shape is not development</h2>
    <p>
      Two countries with the same pyramid share a demographic <em>moment</em> — a similar history of births, deaths and
      migration — not an economy, an institution or a future. Japan's twins in 2026 are Southern European; Qatar's
      are Gulf states with the same guest-worker bulge; a country matched with “Japan 2008” has Japan's age structure of
      that year and nothing else of Japan's. Time-shift matches are a way to see a shape in motion, and a starting
      point for questions, not a forecast: the site makes no claim about what a shape implies for growth, income or
      markets, and the language on every page is kept to what the data shows.
    </p>
  </section>

  <section id="reading" class="mt-10 space-y-3">
    <h2 class="text-xl font-semibold tracking-tight">How to read a pyramid</h2>
    <p>
      Youngest at the bottom, oldest at the top; males to the left, females to the right; each bar is that group's
      share of the whole population, on an axis that stays fixed while you scrub through the years so bars grow and
      shrink in place. A wide base and narrow top (a triangle — <a class="underline" href={example('NER', app.currentYear)}>Niger</a>) means high
      fertility and a young population; straight sides (<a class="underline" href={example('USA', app.currentYear)}>United States</a>) a population
      near replacement; a top-heavy urn (<a class="underline" href={example('JPN', app.currentYear)}>Japan</a>) low fertility and long lives. Look for
      notches (a war, a famine, a one-child policy) and bulges (a baby boom, or migrant workers concentrated in the
      male 25–44 bands as in <a class="underline" href={example('QAT', app.currentYear)}>Qatar</a>), and watch them climb one band every five years.
      The right-hand column on each page names these features and the “stage” (expansive, stationary, constrictive) by
      median age; the ▸ marker flags a bar longer than the axis.
    </p>
  </section>

  <section id="hosting" class="mt-10 space-y-3">
    <h2 class="text-xl font-semibold tracking-tight">Hosting &amp; privacy</h2>
    <p>
      This is a static site on GitHub Pages: no server, no database, no account, no analytics, no cookies. Every
      search runs in your browser over small binary shards ({(meta.sizes.first_paint ?? 0) / 1000 | 0} KB for the first
      view; the {(meta.sizes.shares_d16z / 1e6).toFixed(1)} MB all-years corpus only when you ask for a cross-year search
      or open the time-shift panel). The whole view — country, year, constraints, comparison — is in the URL, so a
      copied link reproduces exactly what you see; the only thing stored on your device is the last country you looked
      at, for the “continue with” button on the home page. Exports (PNG, SVG, CSV) are generated client-side from the
      chart on screen.
    </p>
  </section>

  <section id="attribution" class="mt-10 space-y-3">
    <h2 class="text-xl font-semibold tracking-tight">Attribution &amp; licences</h2>
    <ul class="list-disc space-y-1 pl-5 text-sm">
      {#each meta.attribution as a, i (i)}<li>{a}</li>{/each}
    </ul>
    <p class="text-sm">
      The full notice ships with the data: <a class="underline" href={noticeUrl}>NOTICE</a>. The UN does not endorse this
      site; files under <code>/data</code> are reshaped, share-normalised and 16-bit-quantised derivatives, not the
      original UN files. Design inspiration: <a class="underline" href="https://www.populationpyramid.net" rel="noopener">populationpyramid.net</a>
      (the fixed-axis, youngest-at-the-bottom pyramid and the year scrubber); no data or code from it is used. Code:
      MIT, <a class="underline" href="https://github.com/Eli-Jensen/population-pyramid-explorer" rel="noopener">github.com/Eli-Jensen/population-pyramid-explorer</a>.
      Image encoders used only offline for the experiment above: SigLIP 2 and DINOv2 (Apache-2.0).
    </p>
    <p class="text-xs text-muted">
      Corpus {meta.revision} built {built} ({meta.n_rows.toLocaleString('en-US')} pyramids); evaluation {evalBuilt} on the same data
      (hash <code>{meta.verdicts?.data_hash?.slice(0, 16) ?? '—'}…</code>{meta.verdicts?.stale ? ' — STALE relative to the shipped data' : ''}).
      Current year on this device: {eraChip(app.currentYear)}.
    </p>
  </section>

  <p class="mt-10 text-sm"><a class="underline" href={href({ kind: 'home' })}>← Home</a></p>
</article>
